name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2  # <-- FIXED INDENTATION
      run: |
        ssh -o ServerAliveInterval=60 -tt ubuntu@${{ secrets.EC2_HOST }} <<EOF
        set -e  # Exit on errors

        # Ensure project directory exists with correct permissions
        sudo mkdir -p /var/www/html
        sudo chown -R ubuntu:ubuntu /var/www/html
        cd /var/www/html

        # Check if repo is already cloned
        if [ ! -d ".git" ]; then
          git clone https://github.com/your-username/your-repo.git .
        else
          git pull origin main
        fi

        # Install Nginx if not installed
        if ! command -v nginx &> /dev/null; then
          sudo apt update && sudo apt install -y nginx
        fi

        # Restart Nginx
        sudo systemctl restart nginx

        exit
        EOF
