name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Ensure the project directory exists
          mkdir -p /var/www/html
          cd /var/www/html

          # Initialize Git if not already done
          if [ ! -d ".git" ]; then
            git clone https://github.com/your-username/your-repo.git .
          else
            git pull origin master
          fi

          # Install Nginx if not installed
          if ! command -v nginx &> /dev/null; then
            sudo apt update && sudo apt install -y nginx
          fi

          # Restart Nginx to serve the latest code
          sudo systemctl restart nginx
        EOF
